table User_details
	lineageTag: 08839dbf-280d-4fc0-aab9-f18afd90c5aa

	column 'Customer ID'
		dataType: string
		lineageTag: 148f508e-3049-4675-8e9a-247fc827f815
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column 'Delivery Location Latitude'
		dataType: double
		lineageTag: 17362226-9a92-4c07-8753-196781eae6ae
		summarizeBy: none
		sourceColumn: Delivery Location Latitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Delivery Location Longitude'
		dataType: double
		lineageTag: 10a1bc1b-e42f-4d34-9e7f-bb744ce6ca5f
		summarizeBy: none
		sourceColumn: Delivery Location Longitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Age
		dataType: int64
		formatString: 0
		lineageTag: b8e957a3-4c87-4c4e-a29c-e670bb67594f
		summarizeBy: none
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: bf03b519-2c63-4f6c-bd16-e71dbfd3f789
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 293cbf2a-6111-4221-9f8c-9acb68436cbe
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	partition User_details = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Sanjay Rangasamy\Downloads\QUESTION_Modeling1POWERBI.xlsx"), null, true),
				    User_details_Sheet = Source{[Item="User_details",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(User_details_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Customer ID", type text}, {"Delivery Location Latitude", type number}, {"Delivery Location Longitude", type number}, {"Age", Int64.Type}, {"Gender", type text}, {"City", type text}}),
				    #"Removed Duplicates" = Table.Distinct(#"Changed Type", {"Customer ID"}),
				    #"Filtered Rows" = Table.SelectRows(#"Removed Duplicates", each [Customer ID] <> null and [Customer ID] <> "")
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

